### ISSUE TITLE
Add the project to firebaseopensource.com

### ISSUE THREAD

**Issue by rosariopfernandes** [jsayol/FireSQL#1]
This is a great project and certainly benefits the Firebase Community. I suggest adding it to [firebaseopensource.com](https://firebaseopensource.com/) to be easily discovered. Find out how to add your project on the [Configure Repo](https://github.com/firebase/firebaseopensource.com/blob/master/docs/configure-repo.md) page.

**Comment by jsayol** [comment]
Thanks Rosário, that's a great idea! I'll definitely do that.

**Comment by jsayol** [comment]
Done! https://firebaseopensource.com/projects/jsayol/firesql
