### ISSUE TITLE
Re: Questions about limitations

### ISSUE THREAD

**Issue by Asalem1** [jsayol/FireSQL#2]
Hi @jsayol,

I've read the[ contributing guidelines](https://github.com/jsayol/FireSQL/blob/master/CONTRIBUTING.md) and can't seem to figure out what the best way would be for me to ask this, but after looking at the source code and guide, I can't seem to see whether this repo supports conditional statements (using OR in a query). Would you mind clarifying that for me?

**Comment by jsayol** [comment]
Hey @Asalem1, ORs are indeed supported. Internally this launches 2 separate queries to Firestore and then merges the results before returning them, eliminating any possible duplicates.

You can read more about this in the "[How does FireSQL work?](https://github.com/jsayol/FireSQL/blob/master/README.md#how-does-firesql-work)" section of the README, plus there's also a [list of examples with all the supported operations](https://github.com/jsayol/FireSQL/blob/master/README.md#examples-of-supported-queries).

And sorry about the confusing contributing guidelines, those came straight from the template I used to initially scaffold the library and forgot to change them.

I hope this is helpful, let me know if you run into any issues :)

**Comment by Asalem1** [comment]
Hey @jsayol , thanks for the quick reply! Was about to close out the issue after seeing it in the list of examples and see how it works on the source code:

https://github.com/jsayol/FireSQL/blob/master/src/select/where.ts#L12

Definitely helpful, thanks!
