### ISSUE TITLE
Error: The query requires an index (!?)

### ISSUE THREAD

**Issue by tommtt** [jsayol/FireSQL#34]
Hi guys, I'm trying to run this code:

```
import { FireSQL } from 'firesql';
import 'firebase/firestore';


React.useEffect(() => {
  const fetchData = async () => {
    const showId = await show[0].id;
    console.log(showId)
    const fireSQL = new FireSQL(firebase.firestore());
    const videosPromise = fireSQL.query(`
      SELECT *
      FROM videos
      WHERE uploadBy = '${showId}' 
      ORDER BY uploadDate
    `);
  console.log(videosPromise.then(cities => console.log(cities)))
}
show[0] && fetchData()
}, [show[0]])
```

And it gives me this error:
"The query requires an index. You can create it here: ... "

I thought this library was born to avoid to create firestore indexes...

If I remove "ORDER BY uploadDate" it works, but of course the results are not ordered by upload date.

**Comment by robinparadise** [comment]
You need to click that link error the library print.

You need to create indexes, this library can't change the Firebase Core 🤣

**Comment by tommtt** [comment]
Ah ok, good to know, thanks!
