### ISSUE TITLE
Starter question

### ISSUE THREAD

**Issue by EduardJS** [jsayol/FireSQL#6]
Hello!

I've just found this quite handy repo and by looking at the documentation, I've seen the `LIKE` paragraph.

Knowing that `Firestore` does not have that kind of operation ( while in `Firebase` we could still be doing `orderBy(child).startAt(childValue)` ) I'm quite curious how do you solve it?

Is it something along the lines of `.where('name', '>=', 'joh').orderBy('name', 'ASC')` ?
Trying to look at your source code, in the `where` parsers but not really getting much.

Please advise

**Comment by jsayol** [comment]
Hi @EduardJS! Thanks for your question.

While FireSQL does support the LIKE clause, it's only on a limited basis in the form of `WHERE field LIKE 'value'` (which is exactly the same as `WHERE field = 'value'`) and `WHERE field LIKE 'value%'`.

The second case is the interesting one, which allows to search for values that start with a certain string. Internally, this is achieved by querying for values greater that or equal to `value` but also smaller than the *successor* to `value`.

This is easier to understand with an example, so let's say you want to search for names that start with `"Edua"`. In that case you would do a query with `.where('name', '>=', 'Edua').where('name', '<', 'Edub')`.

The successor is basically obtained by taking the charcode for the last character, in this case `97` for character `a`, and incrementing it by 1 which gives `98`, corresponding to `b`. There's a few more nuances to keep in mind other that just blindly incrementing the last character, so I suggest you take a look at the code if you want to do this yourself. You can see the function I use to compute the successor [here](https://github.com/jsayol/FireSQL/blob/769c90ef0f53435b41f04ace19c3c3f8eb297484/src/utils.ts#L56-L78), which in turn I adapted from the Firebase iOS SDK code.

I hope this helps!

**Comment by EduardJS** [comment]
Hi! Thanks for explaining. Was fiddling with your code meanwhile, and was actually reading your `successorStr` method now. I figured it must have something to do with that and a composite index.

**Comment by jsayol** [comment]
Sure, although there's no need for a composite index in this particular case since both `.where()` are done over the same field.

**Comment by EduardJS** [comment]
Oh you’re right. I was under the impression a composite index was required for ranged operators.
