### ISSUE TITLE
get data collection after document

### ISSUE THREAD

**Issue by edyrkaj** [jsayol/FireSQL#7]
Is it possible to retrieve data from the collections path using select:
`users/docId/collection`

SELECT * FROM users returned only documents but foreach document we can have 
1.  document data
2. collection/documents

Please see at screenshot:
![image](https://user-images.githubusercontent.com/2579367/55715187-816ff080-59f4-11e9-9a70-f4d60ce9e0ac.png)

**Comment by jsayol** [comment]
Hey @edyrkaj. You can initialize FireSQL with a `DocumentReference` to where you want to query. So in your case you could do something like this:

```js
const userId = "123456789";
const userFiresql = new FireSQL(firebase.firestore().doc(`users/${userId}`));

userFiresql.query("SELECT * FROM integrations").then(documents => {
  // ...
});
```

I hope this helps, and let me know if you run into any issues!

**Comment by edyrkaj** [comment]
Thank you @jsayol ;)
