### ISSUE TITLE
The special field __name__

### ISSUE THREAD

**Issue by filipealva** [jsayol/FireSQL#9]
Hey @jsayol,

Is it safe to use `__name__` as the document id? Where did this idea come from?

Is it possible that they change `__name__` internally on Firestore and it stops working?

**Comment by jsayol** [comment]
Hey @filipealva. The `__name__` field is mentioned in several places in the official documentation, so I don't see that changing unless they intentionally decide to introduce a breaking change (and I highly doubt that will be the case here).
